name: CI
on: [pull_request]

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: latest

      - uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: ESLint
        run: pnpm lint

      - name: Typecheck
        run: pnpm typecheck

      - name: Prettier
        run: pnpm format -- --check

      - name: Commitlint
        run: pnpm commitlint --from ${{ github.event.pull_request.base.sha }} --to HEAD
